# Generated by Django 4.0.3 on 2022-05-23 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('dicoms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='main_doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dicomfile_user',
            name='dicomfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dicoms.dicomfile'),
        ),
        migrations.AddField(
            model_name='dicomfile_user',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dicomfile',
            name='access',
            field=models.ManyToManyField(blank=True, related_name='access', through='dicoms.DicomFile_User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dicomfile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dicomfile',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dicoms.patient'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='dicom_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dicoms.dicomfile'),
        ),
    ]
