# Generated by Django 4.0.3 on 2023-01-19 14:05

import dicoms.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicoms', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/'),
        ),
        migrations.AlterField(
            model_name='dicomfile',
            name='file_url',
            field=models.FileField(upload_to='dicoms/', validators=[dicoms.validators.validate_file_extension]),
        ),
    ]
